
---
- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Install PHP
  yum:
    name: php
    state: present

- name: Copy index.php template
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
    mode: 0644

- name: Start and enable Apache
  systemd:
    name: httpd
    state: started
    enabled: yes

