
- name: Copy custom Apache configuration file
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644

- name: Restart Apache to apply new configuration
  systemd:
    name: httpd
    state: restarted

