
---
- name: Install Python 3 and PyMySQL
  yum:
    name:
      - python3
      - python3-PyMySQL
    state: present

- name: Install MySQL
  yum:
    name: mysql-server
    state: present

- name: Start and enable MySQL
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

